### ISSUE TITLE
Found a warning about receive_data method

### ISSUE THREAD

**Issue by li-thy-um** [midori-rb/midori.rb#147]
```
W, [2018-01-23T08:16:56.897635 #1]  WARN -- :  - - Errno::ENOTCONN /app/vendor/bundle/ruby/2.4.0/gems/midori.rb-0.5.0/lib/midori/server.rb:31:in `peeraddr'
/app/vendor/bundle/ruby/2.4.0/gems/midori.rb-0.5.0/lib/midori/server.rb:31:in `block (2 levels) in receive_data'
```
测试环境 docker engine 中没有问题，阿里云 swarm mode 集群部署会报警告
并不影响访问接口

代码缩略版大概是:

```ruby
class ApplicationAPI < Midori::API
  get '/' do
    Midori::Response.new(status: 200, header: {}, body: 'desmodus midori')
  end
end

Midori::Configure.set :bind, '0.0.0.0'
Midori::Configure.set :port, 3000
Midori::Runner.new(Route).start
```

阿里云上的 compose file 大概是：

```
version: '3.2'

services:
  api:
    image: xxxxxxxxx
    logging:
      options:
        max-size: 50M
    ports:
      - 3000
    labels:
      aliyun.routing.port_3000: desmodus-midori
    command: "bundle exec ruby /app/config/midori.rb"
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
```
